name: CNNArch2Caffe2
on:
  push:
  workflow_dispatch:
env:
    GH_TOKEN: ${{ github.token }}
jobs:
   trigger-coopautopilot:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Trigger CoopMontiSimAutopilot pipeline
        run: gh workflow run $WORKFLOW_FILE --repo $REPO  --ref $BRANCH
        env:
          WORKFLOW_FILE: main2.yml
          BRANCH: ${{ github.ref_name }}
          REPO: ${{github.repository}}
          GH_TOKEN: ${{github.token}}
