name: CNNArch2Caffe2
on:
  push:
  workflow_dispatch:
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  masterJobLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Script
        run:    echo "HALLO"
      - name: Run downstream workflow
        run: gh workflow run $WORKFLOW_FILE --repo ${GITHUB_REPOSITORY}
        env:
          WORKFLOW_FILE: main2.yaml      
