name: test
on:
  push:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    if: ${{github.ref_name == 'main'}}
    steps:
      - run: echo "abc"
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - run: echo "abc"
  fourth:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  runs:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  windows_phase:
    needs: [second, fourth, runs]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Finished stage windows"
            echo ${{contains(needs.*.result, 'failure')}}
            echo ${{contains(needs.*.result, 'skipped')}}
            echo ${{!contains(needs.*.result, 'success')}}
          if: ${{!contains(needs.*.result, 'failure')}}
        - run: |
            echo "Failed stage windows"
            echo ${{contains(needs.*.result, 'failure')}}
            echo ${{contains(needs.*.result, 'skipped')}}
            echo ${{contains(needs.*.result, 'success')}}
            exit 1
          if: ${{contains(needs.*.result, 'failure')}}
  third:
    runs-on: ubuntu-latest
    if: ${{ !cancelled()  && contains(needs.windows_phase.result, 'success')}}
    needs: windows_phase
    steps:
     - name: Echo all job results
       run: |
        for result in ${{ needs.windows_phase.result }}; do
          echo "$result"
        done
     - run: echo "abc"
    
