name: test
on:
  push:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    if: ${{github.ref_name == 'main'}}
    steps:
      - run: echo "abc"
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - run: echo "abc"
  fourth:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  windows_phase:
    needs: [second, fourth]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Finished stage windows"
          if: ${{!contains(needs.*.result, 'failure')}}
        - run: |
            echo "Failed stage windows"
            exit 1
          if: ${{contains(needs.*.result, 'failure')}}
  third:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }} # && !contains(needs.*.result, 'skipped') }}
    needs: windows_phase
    steps:
     - name: Echo all job results
       run: |
        for result in ${{ needs.*.result }}; do
          echo "$result"
        done
     - run: echo "abc"
    
