on:
  workflow_dispatch:
name: abc

jobs:
  first:
    runs-on: ubuntu-latest
    if: ${{github.ref_name == 'main'}}
    steps:
      - run: echo "abc"
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - run: echo "abc"
  windows_phase:
    needs: [second,first]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Finished stage windows"
          if: ${{!contains(needs.*.result, 'failure')}}
        - run: |
            echo "Failed stage windows"
            exit 1
          if: ${{contains(needs.*.result, 'failure')}}
  third:
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    needs: windows_phase
    steps:
      - run: echo "abc"
